### ISSUE TITLE
No check in case of rsync is not installed

### ISSUE THREAD

**Issue by lafouine41** [PatchDashboard/patchdashboard#10]
hi, 
There is no check of rsync install which is needed by the install script. By default, on a minimal install of Debian 8, rsync is not present.

However, you did great job :-)

**Comment by metalcated** [comment]
We will get that added, thanks for letting us know. :)

**Comment by faust64** [comment]
This one may be closed as well, I don't have write access, ...

**Comment by lafouine41** [comment]
Coool :-)
