### ISSUE TITLE
Documentation needed: how to remove patchdashboard clients

### ISSUE THREAD

**Issue by phryneas** [PatchDashboard/patchdashboard#11]
Hi,
I'f like to try out patchdashboard, but for the case that it is not what I was wishing for, I would like to know how to clean it from my clients beforehand ;)

Sweeping at the source code, it looks like the client installs to `/opt/patch_client` and `/etc/cron.d/patch-manager`. 

And if I use the push method, I will have to clean a key from `/root/.ssh/authorized_keys`.

Are there any places I am missing?

**Comment by jonsjava** [comment]
* /opt/patch_manager
* /root/.ssh/authorized_keys (each node)
* /etc/apache2/conf.d/patch_manager.conf (Ubuntu/Debian)
* /etc/httpd/conf.d/patch_manager.conf (RHEL/CentOS/Fedora)
* /var/www/patch_manager (if you set it to default)
* /etc/cron.d/patch-manager

I hope this helps!

**Comment by phryneas** [comment]
Thanks that helps a great deal.

Just for clarification: 

* Are any of the files you named (beside the authorized_keys) present on any of the clients?
* does the "pull" mode work without the authorized_keys?

**Comment by jonsjava** [comment]
The pull works without authorized keys, but installs needed scripts into /opt/patch_manager on each client.

**Comment by phryneas** [comment]
Okay, that's everything I need to know - thank you!

This looks promising :+1:
