### ISSUE TITLE
Please provide a way to skip MySQL and Webserver-installation

### ISSUE THREAD

**Issue by rndmh3ro** [PatchDashboard/patchdashboard#3]
Right now the install-script configures the MySQL-database and Apache.
I already have an existing installation of both, so installing and configuring these should be optional.

**Comment by metalcated** [comment]
What OS are you running? The script should detect if you have mysql installed and if so just ask for your root password to create the database. If this is not the case please post your results and we will look into it. As for ditching the installer, that will probably not happy as of now as it does most everything needed to setup the dashboard in one quit step. Any of the maintained applications out there have a good installer. But by all means you are welcome to set this up on your own if you do not like the installer. Thank you for your feedback.

**Comment by rndmh3ro** [comment]
Sorry, I wasn't clear on this. I guess the script detects fine if there's already mysql installed. My point was to provide a custom way without a huge script that can't possibly work on all systems.
