### ISSUE TITLE
certificate on patchdashboard.com

### ISSUE THREAD

**Issue by faust64** [PatchDashboard/patchdashboard#31]
FYI, the certificate used serving https://patchdashboard.com is now invalid.
Validity period section says:
```
Issued On	Monday, December 15, 2014 at 6:39:02 PM
Expires On	Wednesday, December 16, 2015 at 6:39:02 PM
```

**Comment by metalcated** [comment]
Jon, do you have an issuer? I can if not. Just need postmaster to complete
the SSL req.

Mike

**Comment by faust64** [comment]
I assume we can close this issue, as patchdashboard.com is now available through plain http.
Thanks!
