### ISSUE TITLE
Keep getting error "The client shell files do not exist, we recommend you run a new install"

### ISSUE THREAD

**Issue by Anderath** [PatchDashboard/patchdashboard#4]
Running install for: Debian 7.7|head -1|awk {'print '} Debian 7.7|head -1|awk {'print '}|cut -d . -f 1

Please choose an option below

Base Setup:
1) Install
2) Update

Optional:
3) EnableSSL

q) Quit

Choose mode: 2

Mode: Running Update/Upgrade

# Webpage Location, User and Admin information.

Webpage Location Setup

Please enter location for web interface [Default: ]: /patchmgr

Please enter the relative path [Default: /patchmgr/]: 
Notice: Default Location Used: /patchmgr/

# Database Setup information

Enter the MySQL root password: 

Notice: pdashboard updating database tables

# Installing Apache related configurations

Notice:  already exists.

Error: The client shell files do not exist, we recommend you run a new install.

Press 'Enter' to return to the Main Menu.

I am doing the "Update" option to try and go through the install again to troubleshoot and verify that the Mod_Rewrite option for Apache is installed and I get this error. See above for output.

The directory exists /patchmgr and is even chmod'd to 777.

**Comment by jonsjava** [comment]
Assigned issue to metalcated, as he is the primary in the installer. I will also be reviewing the issue.

Reviewing source, I see that the issue happens when it searches for files that it doesn't find.

I'm not sure if we are asking for the current web directory or not, but if we aren't this is the most likely cause of the issue.

##Code to check

```
if [[ "$?" = 0 ]]; then	
auth_key=$(grep auth_key=\" ${new_web_dir}client/*.sh|awk -F\" {'print $2'}|head -n 1)
server_uri=$(grep server_uri=\" ${new_web_dir}client/*.sh|awk -F\" {'print $2'}|head -n 1)
else
echo -e "\e[31mError\e[0m: The client shell files do not exist, we recommend you run a new install.\n"
unset wait
read -p "Press 'Enter' to return to the Main Menu." wait
mainMenu
fi
```

**Comment by metalcated** [comment]
I'll take a look and get it fixed.

**Comment by metalcated** [comment]
Issue has been resolved in the most current commit on the master branch. Please git pull for the most current. If you are running RC1, you may do a git pull in a separate directory and copy only the installer.sh over to the RC1 directory. I cannot guarentee this will work, but it SHOULD work. Please post if you continue to have issues. Thank you and good luck. :)

**Comment by Anderath** [comment]
I have a VM saved in a state so I'll do another git and test it out most likely tomorrow evening and write back.

**Comment by jonsjava** [comment]
Closing ticket due to lack of feedback.  If the issue resurfaces, please resubmit a new ticket.
