### ISSUE TITLE
clients not reporting properly

### ISSUE THREAD

**Issue by sfue83** [PatchDashboard/patchdashboard#6]
in the database I see last checked, but the clients say no updates needed. today almost every single machine wanted updates (debian and ubuntu) CentOS didn't need updates.
if I run the /opt/patch_manager/patch_checker.sh manually everything is fine and reports on how much updates are needed.
could you advice on that? or is eventually an apt-get update needed before apt-get upgrade --just-print ?
Could you eventually make the bug-report/CVE link open in a new tab / window?

thanks in advance

**Comment by jonsjava** [comment]
I will review the scripts.  I do apologize. I will create a gist for each file you need modified. Right now, we are focusing on re-working the code to enterprise-class, while keeping it FOSS.  Because this breaks the system, I think this should take priority, and will personally resolve this one for you.

**Comment by jonsjava** [comment]
Gist: https://gist.github.com/jonsjava/220d183a8c846f7e617b

Just add a new line above "#apt-get --just-print upgrade" that has "apt-get update" on each server, and in client/patch_checker.sh

I'm sorry for that simple oversight.  With as many balls as we've had in the air, we apparently only fully tested CentOS

**Comment by sfue83** [comment]
thanks a lot nice to get updates and help that fast :-)

**Comment by sfue83** [comment]
Everything fine after one day testing all debian / ubuntu clients are reporting the right amount of patches needed.
