### ISSUE TITLE
Use conf-available and conf-enabled instead of conf.d for apache 2.4

### ISSUE THREAD

**Issue by RazarF** [PatchDashboard/patchdashboard#7]
In apache 2.4 - which is installed in Ubuntu 14.04 - conf.d/ is no longer used. Instead, conf-available/ and conf-enabled/ are.

I think you should update the install script to check which version of apache is installed and use the proper directories.

**Comment by jonsjava** [comment]
Thank you. You rock. You can either send a gist of the change or wait a
week or two and we will update our script.

**Comment by RazarF** [comment]
I'm not great with coding, so I'd rather wait a little ;)

**Comment by jonsjava** [comment]
I'll make it a priority.

**Comment by faust64** [comment]
I can confirm current master properly uses `/etc/apache2/conf-available` and `a2enconf` on jessie, which comes with apache 2.4 as well. Using a `test -d`, we may assume it would work on trusty as well.
I think you may close that one.
